/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AcmCert": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DomainRoleArn": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SuperMassiveUK": {
      "type": "sst.aws.Astro"
      "url": string
    }
    "SuperMassiveUkHostedZoneId": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}